/**
 * AIDisclosure — onboarding modal shown once before the user can chat.
 *
 * Store-compliance requirement (Generative AI Safety, 2026 Mandate):
 * - "AI Use Disclosure" must be present in the onboarding flow.
 * - User must explicitly accept before proceeding.
 */
import React from 'react';
import {
  Modal,
  View,
  Text,
  TouchableOpacity,
  StyleSheet,
  ScrollView,
  SafeAreaView,
} from 'react-native';
import { Colors, Spacing, Radius, Typography, Shadow } from '../theme';

interface Props {
  visible: boolean;
  onAccept: () => void;
}

export function AIDisclosure({ visible, onAccept }: Props): React.JSX.Element {
  return (
    <Modal
      visible={visible}
      animationType="slide"
      presentationStyle="pageSheet"
      statusBarTranslucent
    >
      <SafeAreaView style={styles.safe}>
        <ScrollView
          contentContainerStyle={styles.scroll}
          showsVerticalScrollIndicator={false}
        >
          {/* Header */}
          <View style={styles.iconWrap}>
            <Text style={styles.iconEmoji}>🤖</Text>
          </View>
          <Text style={styles.title}>AI-Powered Chat</Text>
          <Text style={styles.subtitle}>Before you start, please read this disclosure.</Text>

          {/* Disclosure body */}
          <View style={styles.card}>
            <Text style={styles.sectionTitle}>What this app does</Text>
            <Text style={styles.body}>
              This app routes your messages to third-party AI language models (OpenAI, Anthropic).
              Responses are generated by AI and may be inaccurate, incomplete, or inappropriate.
            </Text>

            <Text style={styles.sectionTitle}>AI limitations</Text>
            <Text style={styles.body}>
              • AI responses are not a substitute for professional advice (medical, legal, financial).{'\n'}
              • The AI may produce incorrect or misleading information.{'\n'}
              • Conversations may be used to improve AI models per each provider's privacy policy.
            </Text>

            <Text style={styles.sectionTitle}>Your data</Text>
            <Text style={styles.body}>
              Messages are sent to OpenAI and/or Anthropic depending on your selected model.
              Review their privacy policies at openai.com and anthropic.com.
            </Text>

            <Text style={styles.sectionTitle}>Reporting harmful content</Text>
            <Text style={styles.body}>
              You can flag any AI response using the 🚩 button on each message.
              Flagged content is reviewed to improve safety.
            </Text>
          </View>

          {/* CTA */}
          <TouchableOpacity
            style={styles.acceptButton}
            onPress={onAccept}
            accessibilityRole="button"
            accessibilityLabel="Accept AI disclosure and continue"
          >
            <Text style={styles.acceptText}>I Understand — Continue</Text>
          </TouchableOpacity>

          <Text style={styles.footer}>
            By continuing you agree to our Terms of Service and the AI providers' usage policies.
          </Text>
        </ScrollView>
      </SafeAreaView>
    </Modal>
  );
}

const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  scroll: {
    padding: Spacing.lg,
    paddingBottom: Spacing.xxl,
    alignItems: 'center',
  },
  iconWrap: {
    width: 80,
    height: 80,
    borderRadius: Radius.full,
    backgroundColor: Colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: Spacing.md,
    marginTop: Spacing.lg,
  },
  iconEmoji: {
    fontSize: 40,
  },
  title: {
    ...Typography.h1,
    color: Colors.textPrimary,
    textAlign: 'center',
    marginBottom: Spacing.xs,
  },
  subtitle: {
    ...Typography.body,
    color: Colors.textSecondary,
    textAlign: 'center',
    marginBottom: Spacing.lg,
  },
  card: {
    backgroundColor: Colors.surface,
    borderRadius: Radius.lg,
    padding: Spacing.md,
    width: '100%',
    marginBottom: Spacing.lg,
    ...Shadow.sm,
  },
  sectionTitle: {
    ...Typography.label,
    color: Colors.textPrimary,
    marginTop: Spacing.md,
    marginBottom: Spacing.xs,
  },
  body: {
    ...Typography.body,
    color: Colors.textSecondary,
    lineHeight: 22,
  },
  acceptButton: {
    backgroundColor: Colors.primary,
    borderRadius: Radius.full,
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.xl,
    width: '100%',
    alignItems: 'center',
    marginBottom: Spacing.md,
    ...Shadow.sm,
  },
  acceptText: {
    ...Typography.h3,
    color: Colors.textOnPrimary,
  },
  footer: {
    ...Typography.caption,
    color: Colors.textDisabled,
    textAlign: 'center',
    paddingHorizontal: Spacing.md,
  },
});
