/**
 * SettingsScreen — model selection, API info, and app metadata.
 */
import React, { useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  SafeAreaView,
  ScrollView,
  TouchableOpacity,
  Linking,
} from 'react-native';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import type { RootStackParamList } from '../../App';
import { useSettingsStore, PROVIDER_OPTIONS } from '../store/settings.store';
import { OfflineBanner } from '../components/OfflineBanner';
import { ProviderPicker } from '../components/ProviderPicker';
import { useNetInfo } from '../hooks/useNetInfo';
import { Colors, Spacing, Radius, Typography, Shadow } from '../theme';

type Props = NativeStackScreenProps<RootStackParamList, 'Settings'>;

export function SettingsScreen({ navigation }: Props): React.JSX.Element {
  const { selectedProvider, userId } = useSettingsStore();
  const { isConnected } = useNetInfo();
  const [pickerVisible, setPickerVisible] = useState(false);

  const providerColor =
    selectedProvider.provider === 'openai' ? Colors.openai : Colors.anthropic;

  return (
    <SafeAreaView style={styles.safe}>
      {/* Offline banner */}
      <OfflineBanner visible={!isConnected} />

      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity
          onPress={() => navigation.goBack()}
          accessibilityRole="button"
          accessibilityLabel="Go back"
          hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
        >
          <Text style={styles.backBtn}>‹</Text>
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Settings</Text>
        <View style={styles.headerRight} />
      </View>

      <ScrollView contentContainerStyle={styles.scroll}>
        {/* Model section */}
        <Text style={styles.sectionTitle}>AI Model</Text>
        <TouchableOpacity
          style={styles.card}
          onPress={() => setPickerVisible(true)}
          accessibilityRole="button"
          accessibilityLabel={`Selected model: ${selectedProvider.label}. Tap to change.`}
        >
          <View style={[styles.providerDot, { backgroundColor: providerColor }]} />
          <View style={styles.cardContent}>
            <Text style={styles.cardTitle}>{selectedProvider.label}</Text>
            <Text style={styles.cardSubtitle}>
              {selectedProvider.provider === 'openai' ? 'OpenAI' : 'Anthropic'} ·{' '}
              {(selectedProvider.contextWindow / 1000).toFixed(0)}k context window
            </Text>
          </View>
          <Text style={styles.chevron}>›</Text>
        </TouchableOpacity>

        {/* All models */}
        <Text style={styles.sectionTitle}>Available Models</Text>
        <View style={styles.modelGrid}>
          {PROVIDER_OPTIONS.map((opt) => {
            const isActive =
              opt.provider === selectedProvider.provider &&
              opt.model === selectedProvider.model;
            const color = opt.provider === 'openai' ? Colors.openai : Colors.anthropic;
            return (
              <View
                key={`${opt.provider}-${opt.model}`}
                style={[styles.modelChip, isActive && styles.modelChipActive]}
              >
                <View style={[styles.chipDot, { backgroundColor: color }]} />
                <Text
                  style={[styles.chipText, isActive && styles.chipTextActive]}
                  numberOfLines={1}
                >
                  {opt.label}
                </Text>
              </View>
            );
          })}
        </View>

        {/* About section */}
        <Text style={styles.sectionTitle}>About</Text>
        <View style={styles.infoCard}>
          <InfoRow label="App version" value="1.0.0" />
          <InfoRow label="User ID" value={userId.slice(0, 8) + '…'} />
          <InfoRow label="Backend" value="Multi-LLM Orchestration API" />
        </View>

        {/* Privacy links */}
        <Text style={styles.sectionTitle}>Privacy & Terms</Text>
        <View style={styles.infoCard}>
          <LinkRow
            label="OpenAI Privacy Policy"
            url="https://openai.com/privacy"
          />
          <LinkRow
            label="Anthropic Privacy Policy"
            url="https://www.anthropic.com/privacy"
          />
          <LinkRow
            label="Terms of Service"
            url="https://example.com/terms"
          />
        </View>

        {/* AI disclosure reminder */}
        <View style={styles.disclosureBox}>
          <Text style={styles.disclosureIcon}>🤖</Text>
          <Text style={styles.disclosureText}>
            Responses are generated by AI and may be inaccurate. Always verify
            important information. Use the 🚩 button to flag harmful content.
          </Text>
        </View>
      </ScrollView>

      <ProviderPicker
        visible={pickerVisible}
        onClose={() => setPickerVisible(false)}
      />
    </SafeAreaView>
  );
}

function InfoRow({ label, value }: { label: string; value: string }) {
  return (
    <View style={styles.infoRow}>
      <Text style={styles.infoLabel}>{label}</Text>
      <Text style={styles.infoValue}>{value}</Text>
    </View>
  );
}

function LinkRow({ label, url }: { label: string; url: string }) {
  return (
    <TouchableOpacity
      style={styles.infoRow}
      onPress={() => Linking.openURL(url)}
      accessibilityRole="link"
      accessibilityLabel={label}
    >
      <Text style={styles.infoLabel}>{label}</Text>
      <Text style={styles.linkChevron}>›</Text>
    </TouchableOpacity>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.background },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
    backgroundColor: Colors.surface,
  },
  backBtn: { fontSize: 28, color: Colors.primary, lineHeight: 32 },
  headerTitle: { ...Typography.h3, color: Colors.textPrimary },
  headerRight: { width: 32 },
  scroll: { padding: Spacing.md, paddingBottom: Spacing.xxl },
  sectionTitle: {
    ...Typography.label,
    color: Colors.textSecondary,
    marginTop: Spacing.lg,
    marginBottom: Spacing.sm,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  card: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.surface,
    borderRadius: Radius.md,
    padding: Spacing.md,
    gap: Spacing.sm,
    ...Shadow.sm,
  },
  providerDot: { width: 12, height: 12, borderRadius: Radius.full },
  cardContent: { flex: 1 },
  cardTitle: { ...Typography.body, color: Colors.textPrimary, fontWeight: '600' },
  cardSubtitle: { ...Typography.caption, color: Colors.textSecondary, marginTop: 2 },
  chevron: { ...Typography.h3, color: Colors.textDisabled },
  modelGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.xs,
  },
  modelChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: Colors.surface,
    borderRadius: Radius.full,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  modelChipActive: {
    borderColor: Colors.primary,
    backgroundColor: Colors.primaryLight,
  },
  chipDot: { width: 6, height: 6, borderRadius: Radius.full },
  chipText: { ...Typography.caption, color: Colors.textSecondary },
  chipTextActive: { color: Colors.primary, fontWeight: '600' },
  infoCard: {
    backgroundColor: Colors.surface,
    borderRadius: Radius.md,
    overflow: 'hidden',
    ...Shadow.sm,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  infoLabel: { ...Typography.body, color: Colors.textPrimary },
  infoValue: { ...Typography.body, color: Colors.textSecondary },
  linkChevron: { ...Typography.h3, color: Colors.textDisabled },
  disclosureBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: Colors.primaryLight,
    borderRadius: Radius.md,
    padding: Spacing.md,
    marginTop: Spacing.lg,
    gap: Spacing.sm,
    borderWidth: 1,
    borderColor: Colors.primary,
  },
  disclosureIcon: { fontSize: 20 },
  disclosureText: {
    ...Typography.bodySmall,
    color: Colors.primary,
    flex: 1,
    lineHeight: 20,
  },
});
